version: '3'
services:
  jellyfin-spot:
    build: ..
    environment:
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_SERVER_URL=${JELLYFIN_SERVER_URL}
      - DASHBOARD_TITLE=${DASHBOARD_TITLE}
      - DASHBOARD_ICON=${DASHBOARD_ICON}
      - DEBUG=${DEBUG}
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
