version: '3'
services:
  plex-spot:
    build: ..
    environment:
      - PLEX_API_TOKEN=${PLEX_API_TOKEN}
      - PLEX_SERVER_URL=${PLEX_SERVER_URL}
      - DASHBOARD_TITLE=${DASHBOARD_TITLE}
      - DASHBOARD_ICON=${DASHBOARD_ICON}
      - DEBUG=${DEBUG}
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
