version: '3'
services:
  jellyfin-spot:
    container_name: jellyfin-spot
    image: jontstaz/jellyfin-spot
    ports:
      - "8501:8501"
    environment:
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_SERVER_URL=${JELLYFIN_SERVER_URL}
      - DASHBOARD_TITLE=${DASHBOARD_TITLE}
      - DASHBOARD_ICON=${DASHBOARD_ICON}
      - DEBUG=${DEBUG}