version: '3'
services:
  plex-spot:
    build: .
    environment:
      - PLEX_API_TOKEN=${PLEX_API_TOKEN}
      - PLEX_SERVER_URL=${PLEX_SERVER_URL}
    ports:
      - "8501:8501"
    volumes:
      - .:/app

