name: Build and Deploy Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        quiet: true  # Minimize checkout output

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
      continue-on-error: false  # Fail if setup fails

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      continue-on-error: false  # Fail if authentication fails

    - name: Extract version from tag
      id: extract_tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/micro-plex-dashboard:latest
          ${{ secrets.DOCKER_USERNAME }}/micro-plex-dashboard:${{ env.VERSION }}
        quiet: true  # Suppress Docker build logs
      continue-on-error: false  # Fail if build or push fails

    - name: Log out from Docker Hub
      run: docker logout
